# Generated by Django 3.1.6 on 2021-04-19 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210416_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
            preserve_default=False,
        ),
    ]
