# Generated by Django 3.1.6 on 2021-04-19 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_booking_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Customer',
        ),
    ]
