# Generated by Django 3.1.6 on 2021-04-19 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='check_in',
            new_name='Time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='check_out',
        ),
    ]
