# Generated by Django 3.1.6 on 2021-04-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210419_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
