# Generated by Django 3.1.6 on 2021-04-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210422_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Product',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.TextField(),
        ),
    ]
