# Generated by Django 3.1.6 on 2021-04-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210423_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Product',
            field=models.TextField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.TextField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Car', 'Car'), ('Scooter', 'Scooter'), ('Motorcycle', 'Motorcycle')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
